In [2]:
import numpy as np
import pandas as pd

In [3]:
df= pd.read_csv("IMDB Dataset - IMDB Dataset.csv")

In [4]:
df.head(3)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive

In [5]:
df['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

step1

In [6]:
df['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [7]:
df['review'] = df['review'].str.lower()

In [8]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

step2 remove html

In [9]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

In [10]:
text = "<html><body> Sumrit<p> Click <a href = .com</a>"

In [11]:
remove_html_tags(text)

' Sumrit Click '

In [12]:
df['review'] = df['review'].apply(remove_html_tags)

In [13]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [14]:
def remove_url(text):
    pattern = re.compile(r'https?://S+|www\.\S+')
    return pattern.sub(r'',text)

In [15]:
text4 = 'For click https://www.deture.com/delta/note12234acc'

In [16]:
remove_url(text4)

'For click https://'

In [17]:
df['review'] = df['review'].apply(remove_url)

In [18]:
df

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [19]:
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [25]:
exclude = string.punctuation

In [26]:
def remove_punc(text):
    for char in exclude:
        text  = text.replace(char,'')
    return text

In [27]:
text1 = 'string.with.punch?'

In [28]:
remove_punc(text1)

'stringwithpunch'

In [29]:
df['review'] = df['review'].apply(remove_punc)

In [31]:
print(remove_punc(text))

htmlbody Sumritp Click a href  coma

step -5 chatword

In [32]:
chat_words  = {'u2':'you too','BBL':'Be Back Later'}

In [33]:
chat_words

{'u2': 'you too', 'BBL': 'Be Back Later'}

In [34]:
def chat_conversation(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
            
    return "".join(new_text)

In [35]:
chat_conversation('BBL')

'Be Back Later'

In [36]:
chat_words

{'u2': 'you too', 'BBL': 'Be Back Later'}

step 6 spelling coreection

In [38]:
from textblob import TextBlob

In [43]:
incorrect_text = "ceertain seveal chouhrn teh hye"

textBlob = TextBlob(incorrect_text)

textBlob.correct().string

'certain several chouhrn the he'

step 7 removing stepwords

In [48]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ss\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [49]:
STOPWORDS = set(stopwords.words('english'))

In [51]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word in set (stopwords.words('english')):
            new_text.append('')
        else:
            new_text.append(word)
            
    x  = new_text[:]
    new_text.clear()
    return "".join(x)


remove_stopwords('pro my all-time move, a stroy of self')

'proall-timemove,stroyself'

Tokenization

In [52]:
sent1 = "I am going to delhi!"
sent1.split()

['I', 'am', 'going', 'to', 'delhi!']

In [53]:
sent2 = "i am going to delhi . i will stay"
sent2.split('.')

['i am going to delhi ', ' i will stay']

In [54]:
sent3 = "i am going to delhi!"
sent3.split()

['i', 'am', 'going', 'to', 'delhi!']

In [ ]:
import re 
sent3 = "I am going to delhi"

NLTK

In [55]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [56]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ss\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [57]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ss\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [58]:
sent1 = "I am going to visit delhi!"
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [59]:
word_tokenize(sent2)

['i', 'am', 'going', 'to', 'delhi', '.', 'i', 'will', 'stay']

In [60]:
word_tokenize(sent3)

['i', 'am', 'going', 'to', 'delhi', '!']

Stemming

In [61]:
from nltk.stem.porter import PorterStemmer

In [62]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word)for word in text.split()])

In [65]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [66]:
text = 'probably myalltime favourite movie a story'
print(text)

probably myalltime favourite movie a story

In [67]:
stem_words(text)

'probabl myalltim favourit movi a stori'